-- Create stock schema
CREATE SCHEMA STOCK;

-- Create user table
CREATE TABLE STOCK.ST_USER(
	ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    PRIMARY KEY(ID)
);
